version: "3"

services:
  db:
    image: "postgres:12"

    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crusader
      
    volumes:
      - ./volumes/db/:/var/lib/postgresql/data/