export const PLAYER = 'CRUSADER_PLAYER';
export const HOME_TAB = 'CRUSADER_HOME_TAB';
export const CRUSADE_TAB = 'CRUSADER_CRUSADE_TAB';
export const ORDER_OF_BATTLE_TAB = 'CRUSADER_ORDER_OF_BATTLE_TAB';