name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - feature/*
      - fix/*
      - release/*
      - test/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm i -g yarn
    - run: yarn
    - run: yarn run lint
    - run: yarn workspace crusader-web run test
    - run: yarn workspace crusader-web run build